/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;
import java.awt.Frame;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author Tius
 */
public class Form_Menu_Utama extends javax.swing.JFrame {
Connection conn;
   Statement stat;  
   ResultSet res;
   public Connection koneksi;
   String sql;

    /**
     * Creates new form Form_Menu_Utama
     */
    public Form_Menu_Utama() {
        initComponents();         
        setLocationRelativeTo(this);
        koneksi_database();
        tampil_status();
        hak_akses(); 
     }
    
public void koneksi_database(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost/db_pengarsipan","root","");
            stat=koneksi.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
 private void tampil_status(){
     try {
         koneksi_database();
         
         String sql = "select * from tbl_petugas where status = 'AKTIF'";
         res = stat.executeQuery(sql);
         while (res.next()) {
             id_petugas.setText(res.getString("id"));
             nama.setText(res.getString("nama_depan"));
             akses.setText(res.getString("hak_akses"));
             
         }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);
     }
 }
 
  private void status(){
     try {
         stat.executeUpdate("update tbl_petugas set status = 'TIDAK AKTIF' "
                 + "where "
                 + "id='"+id_petugas.getText()+"'"
         );
     } catch (Exception e) {         
         JOptionPane.showMessageDialog(null, "Keterangan Error : " +e);
     }
    
 }
  private void hak_akses(){
      if (akses.getText().equals("Admin")) {
          suratmasuk.setEnabled(true);
          laporan.setEnabled(true);
          opsi.setEnabled(true);
          petugas.setEnabled(true);
      } else {
          suratmasuk.setEnabled(true);
          opsi.setEnabled(true);
          laporan.setEnabled(false);
          laporan.setText("Hanya Admin");
          petugas.setEnabled(false);
          petugas.setText("Hanya Admin");
      }
 
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bG_menu1 = new aplikasi.BG_menu();
        bG_user1 = new aplikasi.BG_user();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id_petugas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        akses = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        suratmasuk = new javax.swing.JMenu();
        disposisi = new javax.swing.JMenu();
        suratkeluar = new javax.swing.JMenu();
        laporan = new javax.swing.JMenu();
        opsi = new javax.swing.JMenu();
        petugas = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENU UTAMA");

        bG_user1.setBackground(new java.awt.Color(255, 255, 255));
        bG_user1.setPreferredSize(new java.awt.Dimension(423, 267));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID");

        id_petugas.setBackground(new java.awt.Color(255, 255, 255));
        id_petugas.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        id_petugas.setText("id");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nama");

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        nama.setText("nama");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Akses");

        akses.setBackground(new java.awt.Color(255, 255, 255));
        akses.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        akses.setText("akses");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(akses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_petugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(akses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bG_user1Layout = new javax.swing.GroupLayout(bG_user1);
        bG_user1.setLayout(bG_user1Layout);
        bG_user1Layout.setHorizontalGroup(
            bG_user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bG_user1Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        bG_user1Layout.setVerticalGroup(
            bG_user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bG_user1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("APLIKASI PENGARSIPAN SURAT");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("SMK NEGERI 2 KOTA BEKASI");

        javax.swing.GroupLayout bG_menu1Layout = new javax.swing.GroupLayout(bG_menu1);
        bG_menu1.setLayout(bG_menu1Layout);
        bG_menu1Layout.setHorizontalGroup(
            bG_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bG_menu1Layout.createSequentialGroup()
                .addGap(0, 1040, Short.MAX_VALUE)
                .addComponent(bG_user1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bG_menu1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(bG_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bG_menu1Layout.setVerticalGroup(
            bG_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bG_menu1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, Short.MAX_VALUE)
                .addComponent(bG_user1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 255));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 80));

        suratmasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon64/shop-26-64.png"))); // NOI18N
        suratmasuk.setText("SURAT MASUK");
        suratmasuk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        suratmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                suratmasukMousePressed(evt);
            }
        });
        suratmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suratmasukActionPerformed(evt);
            }
        });
        jMenuBar1.add(suratmasuk);

        disposisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon64/message-already-read.png"))); // NOI18N
        disposisi.setText("DISPOSISI");
        disposisi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        disposisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                disposisiMousePressed(evt);
            }
        });
        jMenuBar1.add(disposisi);

        suratkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon64/email-send.png"))); // NOI18N
        suratkeluar.setText("SURAT KELUAR");
        suratkeluar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        suratkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                suratkeluarMousePressed(evt);
            }
        });
        jMenuBar1.add(suratkeluar);

        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon64/product-sales-report.png"))); // NOI18N
        laporan.setText("LAPORAN");
        laporan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                laporanMousePressed(evt);
            }
        });
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        jMenuBar1.add(laporan);

        opsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon64/gear_setting_option-64.png"))); // NOI18N
        opsi.setText("PENGATURAN");
        opsi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        petugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon32/090-32.png"))); // NOI18N
        petugas.setText("Petugas");
        petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugasActionPerformed(evt);
            }
        });
        opsi.add(petugas);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon32/run_exit_2-32.png"))); // NOI18N
        jMenuItem3.setText("Keluar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        opsi.add(jMenuItem3);

        jMenuBar1.add(opsi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bG_menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bG_menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        status();
        this.dispose();
        new Form_login().show();
        JOptionPane.showMessageDialog(null,"Anda Berhasil Logout !!");         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void suratmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suratmasukActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_suratmasukActionPerformed

    private void suratmasukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suratmasukMousePressed
  new Form_Surat_Masuk().show();       // TODO add your handling code here:
    }//GEN-LAST:event_suratmasukMousePressed

    private void disposisiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disposisiMousePressed
new Form_Disposisi().show();        // TODO add your handling code here:
    }//GEN-LAST:event_disposisiMousePressed

    private void suratkeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suratkeluarMousePressed
new Form_Surat_Keluar().show();        // TODO add your handling code here:
    }//GEN-LAST:event_suratkeluarMousePressed

    private void petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasActionPerformed
new Form_Data_Petugas().show();        // TODO add your handling code here:
    }//GEN-LAST:event_petugasActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_laporanActionPerformed

    private void laporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMousePressed
new Laporan().show();    
hak_akses();// TODO add your handling code here:
    }//GEN-LAST:event_laporanMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Menu_Utama mu = new Form_Menu_Utama();
                mu.setExtendedState(MAXIMIZED_BOTH);
                mu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akses;
    private aplikasi.BG_menu bG_menu1;
    private aplikasi.BG_user bG_user1;
    private javax.swing.JMenu disposisi;
    private javax.swing.JLabel id_petugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu laporan;
    private javax.swing.JLabel nama;
    private javax.swing.JMenu opsi;
    private javax.swing.JMenuItem petugas;
    private javax.swing.JMenu suratkeluar;
    private javax.swing.JMenu suratmasuk;
    // End of variables declaration//GEN-END:variables
}
